# Generated by Django 5.2.4 on 2025-07-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisoes',
            name='numero_bo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prisoes',
            name='numero_documento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prisoes',
            name='placa',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
