# Generated by Django 5.2.4 on 2025-07-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_prisoes_ocorrencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocorrencia',
            options={'verbose_name': 'Ocorrência', 'verbose_name_plural': 'Ocorrências'},
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='estrutura_criminal',
            field=models.CharField(max_length=11),
        ),
    ]
