# Generated by Django 5.2.4 on 2025-07-26 22:10

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension



class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_ocorrencia_options_and_more'),
    ]

    operations = [
        CreateExtension('unaccent'),
    ]
