# Generated by Django 5.2.4 on 2025-07-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20250726_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='estrutura_criminal',
            field=models.CharField(choices=[('OPORTUNISTA', 'Oportunista'), ('RECEPTACAO', 'Receptação'), ('QUADRILHA', 'Quadrilha')], max_length=11),
        ),
    ]
