# Generated by Django 5.2.4 on 2025-07-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_ocorrencia_estrutura_criminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurtoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ocorrencia', models.DateField(db_index=True, verbose_name='Data da Ocorrência')),
                ('status', models.CharField(choices=[('AGUARDANDO_GEO', 'Aguardando Geocodificação'), ('GEO_FALHOU', 'Falha na Geocodificação'), ('AGUARDANDO_VERIFICACAO', 'Aguardando Verificação'), ('VERIFICADO', 'Verificado')], db_index=True, default='AGUARDANDO_GEO', max_length=22)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('tipo_de_equipamento', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
