# Generated by Django 5.2.4 on 2025-07-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_furtoequipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furtoequipamento',
            name='numero',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
