# Generated by Django 5.2.4 on 2025-07-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_furtoequipamento_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furtoequipamento',
            name='tipo_de_equipamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
