# Generated by Django 5.2.4 on 2025-07-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_furtoequipamento_tipo_de_equipamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='furtoequipamento',
            options={'verbose_name': 'Furto de Equipamento', 'verbose_name_plural': 'Furtos de Equipamento'},
        ),
        migrations.AlterField(
            model_name='furtoequipamento',
            name='uf',
            field=models.CharField(default='PR', max_length=2, verbose_name='UF'),
        ),
    ]
