# Generated by Django 5.2.4 on 2025-07-30 18:14

from django.db import migrations

sinonimos = {
    'fibra óptica': 'Fibra Óptica',
    'Cabos Óticos': 'Fibra Óptica',
    'Cabos Metálicos': 'Metálicos',
    'Metalicos': 'Metálicos',
    'baterias de litio': 'Bateria de Lítio',
    'Bateria de litio': 'Bateria de Lítio',
    'caixa de emenda': 'Caixa de Emenda'
}


def clean_and_standardize_tipos_estrutura(apps, schema_editor):
    FurtoEquipamento = apps.get_model('main', 'FurtoEquipamento')
    db_alias = schema_editor.connection.alias

    for furto in FurtoEquipamento.objects.using(db_alias).all().iterator():
        if furto.tipo_de_equipamento:
            furto.tipo_de_equipamento = furto.tipo_de_equipamento.strip()
            if sinonimos.get(furto.tipo_de_equipamento):
                furto.tipo_de_equipamento = sinonimos[furto.tipo_de_equipamento]

            furto.save(update_fields=['tipo_de_equipamento'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_furtoequipamento_options_and_more'),
    ]

    operations = [
        migrations.RunPython(clean_and_standardize_tipos_estrutura)
    ]
