# Generated by Django 5.2.4 on 2025-07-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_clean_and_standardize_tipo_equipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='placa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
