# Generated by Django 5.2.4 on 2025-09-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_ocorrencia_numero_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='numero_bo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
